"""add approved Gmail outreach and sourced contacts

Revision ID: 7d1022345283
Revises: fe71f5002a69
Create Date: 2026-10-09 18:15:47.977179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7d1022345283'
down_revision: Union[str, Sequence[str], None] = 'fe71f5002a69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gmail_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('encrypted_refresh_token', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('contact_type', sa.String(length=20), nullable=False),
    sa.Column('value', sa.String(length=320), nullable=False),
    sa.Column('source_url', sa.String(length=2000), nullable=False),
    sa.Column('direct_url', sa.Text(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('usable', sa.Boolean(), nullable=False),
    sa.Column('discovered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('restaurant_id', 'contact_type', 'value', 'source_url', name='uq_contact_source')
    )
    op.create_table('approved_emails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('outreach_id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('recipient', sa.String(length=320), nullable=False),
    sa.Column('sender', sa.String(length=320), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('source_url', sa.String(length=2000), nullable=False),
    sa.Column('mime_message_id', sa.String(length=255), nullable=False),
    sa.Column('gmail_message_id', sa.String(length=255), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('attempted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['outreach_id'], ['outreach_attempts.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mime_message_id'),
    sa.UniqueConstraint('outreach_id')
    )
    op.alter_column('outreach_attempts', 'sent_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               server_default=None,
               existing_server_default=sa.text('now()'))
    # Alembic does not automatically detect edits to CHECK constraints.
    op.drop_constraint('ck_outreach_status', 'outreach_attempts', type_='check')
    op.create_check_constraint('ck_outreach_status', 'outreach_attempts',
        "status IN ('sent', 'scheduling', 'rejected', 'tasting', 'completed', 'email_approved', 'email_sending', 'email_failed', 'email_unknown')")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    connection = op.get_bind()
    if connection.scalar(sa.text("SELECT EXISTS(SELECT 1 FROM approved_emails) OR EXISTS(SELECT 1 FROM gmail_accounts) OR EXISTS(SELECT 1 FROM contacts)")):
        raise RuntimeError("Refusing downgrade: Gmail/contact records would be lost. Export and resolve them explicitly first.")
    op.drop_constraint('ck_outreach_status', 'outreach_attempts', type_='check')
    op.create_check_constraint('ck_outreach_status', 'outreach_attempts',
        "status IN ('sent', 'scheduling', 'rejected', 'tasting', 'completed')")
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('outreach_attempts', 'sent_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               server_default=sa.text('now()'))
    op.drop_table('approved_emails')
    op.drop_table('contacts')
    op.drop_table('gmail_accounts')
    # ### end Alembic commands ###
