"""add creator profiles and isolated outreach drafts

Revision ID: a3bb18d68791
Revises: 7d1022345283
Create Date: 2026-10-09 23:50:00.040760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a3bb18d68791'
down_revision: Union[str, Sequence[str], None] = '7d1022345283'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('creator_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator_name', sa.String(length=100), nullable=False),
    sa.Column('tiktok_url', sa.String(length=2000), nullable=False),
    sa.Column('views_over', sa.BigInteger(), nullable=False),
    sa.Column('shares_over', sa.BigInteger(), nullable=False),
    sa.Column('minimum_video_views', sa.BigInteger(), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('id = 1', name='ck_single_creator'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('outreach_drafts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.String(length=36), nullable=False),
    sa.Column('creator_profile_id', sa.Integer(), nullable=False),
    sa.Column('google_place_id', sa.String(length=255), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('factual_inputs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('model_selection', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('prompt_version', sa.String(length=100), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=True),
    sa.Column('message_text', sa.Text(), nullable=True),
    sa.Column('error_code', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("channel IN ('email', 'tiktok', 'instagram')", name='ck_draft_channel'),
    sa.CheckConstraint("status IN ('generating', 'ready', 'failed')", name='ck_draft_status'),
    sa.ForeignKeyConstraint(['creator_profile_id'], ['creator_profiles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_id')
    )
    op.create_index(op.f('ix_outreach_drafts_created_at'), 'outreach_drafts', ['created_at'], unique=False)
    op.create_index(op.f('ix_outreach_drafts_google_place_id'), 'outreach_drafts', ['google_place_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    connection = op.get_bind()
    if connection.scalar(sa.text("SELECT EXISTS (SELECT 1 FROM outreach_drafts) OR EXISTS (SELECT 1 FROM creator_profiles)")):
        raise RuntimeError("Refusing to delete saved creator profiles or draft history. Back up and review the data first.")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_outreach_drafts_google_place_id'), table_name='outreach_drafts')
    op.drop_index(op.f('ix_outreach_drafts_created_at'), table_name='outreach_drafts')
    op.drop_table('outreach_drafts')
    op.drop_table('creator_profiles')
    # ### end Alembic commands ###
