"""create restaurants table

Revision ID: d0d790716ec0
Revises: 
Create Date: 2026-10-04 00:11:40.965361 (just for documentation. Alembic orders migrations through revision identifiers, not timestamps)

"""
from typing import Sequence, Union  #fields that might contain 1 revision, multiple revisions or no revision

from alembic import op #op provides alembic operations like creating tables, adding cols & removing constraints
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0d790716ec0' 
down_revision: Union[str, Sequence[str], None] = None 
branch_labels: Union[str, Sequence[str], None] = None #optinal names to migration branches
depends_on: Union[str, Sequence[str], None] = None
# Union means value maybe anything inside []
# Sequence[str] means ordered collection of strs, normally a tuple or list


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restaurants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('google_place_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('google_place_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('restaurants')
    # ### end Alembic commands ###
    # destructive as would delete all data from restaurants table
