"""add restaurant discovery fields

Revision ID: eaf4661c3d3c
Revises: d0d790716ec0
Create Date: 2026-10-04 15:12:03.411289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eaf4661c3d3c'
down_revision: Union[str, Sequence[str], None] = 'd0d790716ec0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurants', sa.Column('category', sa.String(length=100), nullable=True))
    op.add_column('restaurants', sa.Column('address', sa.Text(), nullable=True))
    op.add_column('restaurants', sa.Column('area', sa.String(length=100), nullable=True))
    op.add_column('restaurants', sa.Column('website_url', sa.Text(), nullable=True))
    op.add_column('restaurants', sa.Column('rating', sa.Float(), nullable=True))
    op.add_column('restaurants', sa.Column('review_count', sa.Integer(), nullable=True))
    op.add_column('restaurants', sa.Column('price_level', sa.String(length=50), nullable=True))
    op.add_column('restaurants', sa.Column('business_status', sa.String(length=50), nullable=True))
    op.add_column('restaurants', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('restaurants', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurants', 'updated_at')
    op.drop_column('restaurants', 'created_at')
    op.drop_column('restaurants', 'business_status')
    op.drop_column('restaurants', 'price_level')
    op.drop_column('restaurants', 'review_count')
    op.drop_column('restaurants', 'rating')
    op.drop_column('restaurants', 'website_url')
    op.drop_column('restaurants', 'area')
    op.drop_column('restaurants', 'address')
    op.drop_column('restaurants', 'category')
    # ### end Alembic commands ###
