"""add persistent tasting plans

Revision ID: fe71f5002a69
Revises: da5c9c4314ca
Create Date: 2026-10-09 13:43:14.840679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe71f5002a69'
down_revision: Union[str, Sequence[str], None] = 'da5c9c4314ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tastings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('outreach_id', sa.Integer(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('address', sa.String(length=1000), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['outreach_id'], ['outreach_attempts.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('outreach_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tastings')
    # ### end Alembic commands ###
